### ISSUE TITLE
Blank screen after admin login.

### ISSUE THREAD

**Issue by sergeytolkachyov** [compuphase/sphider-pdo#1]
Server: PHP Version 7.0.17, mysqlnd 5.0.12-dev - 20150407.

**Comment by compuphase** [comment]
Confirmed: this is an incompatibility with PHP 7.x.
I will start debugging it.

**Comment by compuphase** [comment]
Correction submitted in revision efcc9f2d0d0fe0dda1000d829826898cd5e550eb
