### ISSUE TITLE
Error when allowing spider to leave domain

### ISSUE THREAD

**Issue by Sooshiii** [compuphase/sphider-pdo#9]
I'm using PHP 7.2.18,

When allowing spider to leave the url, I get:
Notice: Undefined index: path in \admin\spiderfuncs.php on line 431

```
    //parent url might be used to build an url from relative path
    $parent_url = remove_file_from_url($parent_url);
    $parent_url_parts = parse_url($parent_url);

    if (substr($url, 0, 1) == '/') {
        $url = $parent_url_parts['scheme']."://".$parent_url_parts['host'].$url;
    } else if (!isset($urlparts['scheme'])) {
        $url = $parent_url.$url;
    }
    $url_parts = parse_url($url);

    // this is line 431
    $urlpath = $url_parts['path'];
```

**Comment by compuphase** [comment]
I just fixed the error on that line. When looking through the source code, it is likely there will be more errors of the same kind. Sphider assumes that undefined indexes simply evaluate to an empty string without any warning/error.
